
import paralleldots
paralleldots.set_api_key( "xZknTEd2sAcJ0I6o3d7RrMLdIRtEar0aRlgwMdqyvpc" )
paralleldots.get_api_key()

#from paralleldots import hit_count, specific_hit_count
#
## View the number of API hits made and hits remaining
#hit_count()
#
## View the number of hits made for a specific API by using function name as a String
#specific_hit_count( "multilang_sentiment" )

api_key   = "xZknTEd2sAcJ0I6o3d7RrMLdIRtEar0aRlgwMdqyvpc"
text      = "Prime Minister Narendra Modi tweeted a link to the speech Human Resource Development Minister Smriti Irani made in the Lok Sabha during the bate on the ongoing JNU row and the suicide of Dalit scholar Rohith Vemula at the Hyderabad Central University."
path      = "/home/my_computer/Downloads/image_1.jpg"
lang_code = "fr"
category  = { "finance": [ "markets", "economy", "shares" ], "world politics": [ "diplomacy", "UN", "war" ], "india": [ "congress", "india", "bjp" ] }
url       = "http://i.imgur.com/klb812s.jpg"
data      =  [ "drugs are fun", "don\'t do drugs, stay in school", "lol you a fag son", "I have a throat infection" ]


paralleldots.set_api_key( api_key )
print( "API Key: %s" % paralleldots.get_api_key() )

text = "Prime Minister Narendra Modi tweeted a link to the speech Human Resource Development Minister Smriti Irani made in the Lok Sabha during the bate on the ongoing JNU row and the suicide of Dalit scholar Rohith Vemula at the Hyderabad Central University."
print( "\nAbuse" )
print( paralleldots.abuse( text ) )


print( "\nEmotion" )
print( paralleldots.emotion( text ) )

print( "\nBatch Emotion" )
print( paralleldots.batch_emotion( data ) )
{'batch': [{'emotion': {'probabilities': {'Sarcasm': 0.14361357966835644, 'Angry': 0.08368749025924326, 'Sad': 0.025132654797074747, 'Fear': 0.344180628127824, 'Bored': 0.06818537695928778, 'Excited': 0.2082173830066366, 'Happy': 0.1269828871815771}, 'emotion': 'Fear'}, 'code': 200}, {'emotion': {'probabilities': {'Sarcasm': 0.09578231410218406, 'Angry': 0.28458333402617014, 'Sad': 0.05735552847026735, 'Fear': 0.13348989058422842, 'Bored': 0.21483391837268373, 'Excited': 0.10118401124107868, 'Happy': 0.11277100320338784}, 'emotion': 'Angry'}, 'code': 200}, {'emotion': {'probabilities': {'Sarcasm': 0.11124312097614852, 'Angry': 0.1216389498218648, 'Sad': 0.05410169293913279, 'Fear': 0.18020579627989994, 'Bored': 0.2922536573298578, 'Excited': 0.16457090063285224, 'Happy': 0.07598588202024392}, 'emotion': 'Bored'}, 'code': 200}, {'emotion': {'probabilities': {'Sarcasm': 0.05327575096045899, 'Angry': 0.46982189055546925, 'Sad': 0.3672790882763135, 'Fear': 0.09443579921654321, 'Bored': 0.005730775686542725, 'Excited': 0.004337021311595699, 'Happy': 0.005119673993076841}, 'emotion': 'Angry'}, 'code': 200}]}

print( "\nIntent" )
print( paralleldots.intent( text ) )
{"probabilities":{"marketing":0.042, "spam/junk":0.003, "news":0.927, "feedback/opinion":0.024, "query":0.004}, "usage":"By accessing ParallelDots API or using information generated by ParallelDots API, you are agreeing to be bound by the ParallelDots API Terms of Use: http://www.paralleldots.com/terms-and-conditions", "intent":"news"}

print( "\nBatch Intent" )
print( paralleldots.batch_intent( data ) )
{'batch': [{'probabilities': {'marketing': 0.116, 'spam/junk': 0.66, 'query': 0.002, 'feedback/opinion': 0.141, 'news': 0.08}, 'code': 200, 'intent': 'spam/junk'}, {'probabilities': {'marketing': 0.106, 'spam/junk': 0.423, 'query': 0.027, 'feedback/opinion': 0.393, 'news': 0.051}, 'code': 200, 'intent': 'spam/junk'}, {'probabilities': {'marketing': 0.001, 'spam/junk': 0.664, 'query': 0.001, 'feedback/opinion': 0.333, 'news': 0.001}, 'code': 200, 'intent': 'spam/junk'}, {'probabilities': {'marketing': 0.0, 'spam/junk': 0.124, 'query': 0.404, 'feedback/opinion': 0.469, 'news': 0.004}, 'code': 200, 'intent': 'feedback/opinion'}]}

print( "\nSentiment" )
print( paralleldots.sentiment( text ) )
{"probabilities":{"positive":0.266, "neutral":0.549, "negative":0.185}, "usage":"By accessing ParallelDots API or using information generated by ParallelDots API, you are agreeing to be bound by the ParallelDots API Terms of Use: http://www.paralleldots.com/terms-and-conditions", "sentiment":"neutral"}

print( "\nBatch Sentiment" )
print( paralleldots.batch_sentiment( data ) )
{'batch': [{'probabilities': {'positive': 0.69, 'neutral': 0.265, 'negative': 0.046}, 'code': 200, 'sentiment': 'positive'}, {'probabilities': {'positive': 0.061, 'neutral': 0.578, 'negative': 0.361}, 'code': 200, 'sentiment': 'neutral'}, {'probabilities': {'positive': 0.527, 'neutral': 0.198, 'negative': 0.275}, 'code': 200, 'sentiment': 'positive'}, {'probabilities': {'positive': 0.077, 'neutral': 0.015, 'negative': 0.908}, 'code': 200, 'sentiment': 'negative'}]}

paralleldots.usage()